name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.7]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r CIrequirements.txt
    - name: Building Containers
      run: |
        python create_env.py
        docker compose up --build -d
        
    - name: Run Tests
      run: |
        docker exec sampleshareMB_web sh -c "python manage.py makemigrations"
        docker exec sampleshareMB_web sh -c "python manage.py migrate"
        docker exec sampleshareMB_web sh -c "python manage.py test"
